# docker-compose.dev.yml
# 開発環境用の完全な設定ファイル
# 起動コマンド: docker-compose -f docker-compose.dev.yml up --build

services:
  # バックエンドサービス (FastAPI)
  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app # ホストのソースコードをコンテナに同期
    depends_on:
      db:
        condition: service_healthy

  # フロントエンドサービス (Next.js)
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app    # ホストのソースコードをコンテナに同期
      - /app/node_modules # node_modulesはコンテナ内のものを使用
    depends_on:
      - backend

  # 開発用データベースサービス (MySQL)
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306" # ホストPCからDBに直接接続する場合のポート
    volumes:
      - mysql-data:/var/lib/mysql # データを永続化する
    healthcheck: # dbサービスが起動してから開始する
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

# データベースのデータを永続化するためのVolumeを定義
volumes:
  mysql-data: